name: OWASP Dependency Check

on:
  pull_request:
    branches:
      - master

jobs:
  dependency-check:
    name: OWASP Dependency Check
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Setup Java
        if: ${{ contains(github.event.pull_request.head.repo.language, 'Java') }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run OWASP Dependency Check
        uses: owasp/dependency-check-action@v4
        with:
          project: '${{ github.event.pull_request.head.repo.name }}'
          scan_type: 'All'
          report_format: 'HTML,JSON'
          fail_on_severity: 'HIGH' 

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: dependency-check-report
